/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/library/**/*.{js,ts,jsx,tsx,html}",
    "./library.html",
  ],
  theme: {
    extend: {
      colors: {
        void: '#08090a',
        carbon: '#0f1011',
        obsidian: '#161718',
        graphite: '#23252a',
        smoke: '#383b3f',
        ash: '#62666d',
        fog: '#8a8f98',
        mist: '#d0d6e0',
        bone: '#e5e5e6',
        paper: '#ffffff',
        'acid-lime': '#e4f222',
        'pulse-green': '#27a644',
        'coral-red': '#eb5757',
        'signal-teal': '#02b8cc',
        'iris-violet': '#6366f1',
        lavender: '#8b5cf6',
      },
      fontFamily: {
        sans: [
          'Inter Variable',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'sans-serif',
        ],
        mono: [
          'Berkeley Mono',
          'JetBrains Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
      },
      letterSpacing: {
        tightest: '-0.022em',
        tighter: '-0.013em',
        tight: '-0.011em',
      },
      borderRadius: {
        sm: '2px',
        md: '6px',
        xl: '12px',
        badge: '4px',
        input: '6px',
        button: '9999px',
        card: '12px',
        pill: '9999px',
      },
      boxShadow: {
        hairline: 'rgb(35, 37, 42) 0px 0px 0px 1px inset',
        'hairline-subtle': 'rgba(255, 255, 255, 0.05) 0px 0px 0px 1px inset',
        card: 'rgba(0, 0, 0, 0.4) 0px 2px 4px 0px, rgb(35, 37, 42) 0px 0px 0px 1px inset',
        modal: 'rgba(8, 9, 10, 0.8) 0px 16px 48px 0px, rgb(35, 37, 42) 0px 0px 0px 1px',
        lime: '0px 2px 8px rgba(228, 242, 34, 0.15)',
      },
    },
  },
  plugins: [],
}
